export const PROFILE_TOGGLE_SHOW = "PROFILE_TOGGLE_SHOW";
export const PROFILE_DROP_NAME = "PROFILE_DROP_NAME";
export const PROFILE_SET_NAME = "PROFILE::SET_NAME";
export const SET_AUTH = "PROFILE::SET_AUTH";
export const SET_ERROR = "PROFILE::SET_ERROR";
